[features]
seeds = false
skip-lint = false
[programs.devnet]
my_app = "8NNEizqLcRU41FZo7gZkNmAABMSbuZbGKm2WhNRp2zYT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/username042111/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
